version: '3.8'

services:
  reminder-bot:
    build: .
    container_name: reminder-bot
    restart: unless-stopped
    ports:
      - "5000:5000"  # 保持内外端口一致
    environment:
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}
      - PORT=5000  # 明确指定端口
